# Generated by Django 4.2.11 on 2025-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("writer", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("write_date", models.DateTimeField()),
                ("category", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("keywords", models.TextField()),
                ("embedding", models.BinaryField(null=True)),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "news_article",
                "managed": True,
            },
        ),
    ]
