# Generated by Django 4.2.11 on 2025-05-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_articleread"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsarticle",
            options={"managed": False},
        ),
    ]
