# Generated by Django 4.2.11 on 2025-05-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newsarticle_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsarticle",
            options={"managed": True},
        ),
    ]
