# Generated by Django 4.2.11 on 2025-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_newsarticle_options"),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
