# Generated by Django 4.2.11 on 2025-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_auto_20250516_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
